# This file is to test and see if the Docker Images are being
# built properly.
#
# If there are any issues with any of the Dockerfile or
# docker-compose.yml files, then this GitHub action will fail,
# helping us identify that something is wrong with the
# Docker scripts.
name: Docker Image Build Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: docker-compose build
      run: docker-compose build --no-cache
